[package]
name = "proc_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-derived = "0.9.2"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }
getrandom = { version = "0.3.1", features = ["wasm_js"] }

[lib]
proc-macro = true
